name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testSender *.cpp ./sourceFiles/*.cpp
      
    - name: build receiver 
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testreceiver Receiver_tester.c *c ./sourceFiles/ReceiverData.c
      
    - name: run
      run: ./testSender
      
    - name: Pipeline sender/receiver
      run: ./testsender | ./testreceiver

    - name: collect coverage
      run: gcovr -r . --html --html-details -o coverage.html --print-summary

    - name: create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 21
